version: '3'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  backend:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    environment:
      - REACT_APP_OPENAI_API_KEY=${REACT_APP_OPENAI_API_KEY}
      - PORT=8080

networks:
  mynetwork:
    driver: bridge
